- type: job
  id: NFPirate
  name: job-name-nf-pirate
  description: job-description-nf-pirate
  playTimeTracker: JobPirate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # frontier: 24 hrs / 4 shifts | CS: 12 hours / 2 shifts
    - !type:RoleTimeRequirement
      role: JobPirate
      time: 3600 # CS: 1 hour
#    - !type:DepartmentTimeRequirement # CS: swaps the playtime requirement to literally just be an hour of the role itself.
#      department: Security
#      time: 10800 # 3 hrs
  startingGear: NFPirateGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconNFPirate"
  supervisors: job-supervisors-nf-pirate
  weight: 20
  displayWeight: 20
  setPreference: true
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: AutoPirate
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
    - type: DisableSuitSensors
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: NFPirateGear
  equipment:
    belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
  storage:
    back:
    - AppraisalTool
