- type: job
  id: DirectorOfCare
  name: job-name-doc
  description: job-description-doc
  playTimeTracker: JobDirectorOfCare
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hrs
    - !type:RoleTimeRequirement
      role: JobDirectorOfCare # CS: JobDirectorOfCare
      time: 3600 # CS: 1 hr of itself
  whitelisted: true
  startingGear: DocGear
  alwaysUseSpawner: true
  icon: "JobIconDoc"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 55 # Second from the top
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: MedicalBountyBankPayment # any medical bounties sold go directly into the bank
        account: Medical
      - type: CoolStationDirectorOfCare
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DocGear
  equipment:
    pocket1: HypoMini
    pocket2: MedicalAppraisalTool
  storage:
    back:
    - StationAdministrationConsoleFlatpack
    - MobileComputerTabletopCommsFlatpack
    - BoxFolderMedicalDoctor
    - RubberStampDoc
